import Head from "next/head"
import React, { useEffect, useRef } from 'react'
import Transition from "../components/Transition"
import gsap from 'gsap';


function about() {
    const about = gsap.timeline();
    const abouth1 = useRef(null);
    const aboutimg = useRef(null);
    useEffect(() => {
        about.from(abouth1.current, {
            duration: .6,
            skewX: 10,
            x: -100,
            opacity: 0
        }, "-=3.5")
        about.from(aboutimg.current, {
            duration: .5,
            y: -200,
            opacity: 0
        }, "-=3")
    })


    return (
        <div>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Transition timeline={about} />
            <div className="about-image about-overlay" ref={aboutimg}></div>
            <div className="container-about">
                <h1 ref={abouth1}>about Page</h1>
            </div>
        </div>
    )

}

export default about