import Head from "next/head"
import React, { useEffect, useRef } from 'react'
import Transition from "../components/Transition"
import gsap from 'gsap';


function contact() {
    const contact = gsap.timeline();
    const contacth1 = useRef(null);
    const contactimg = useRef(null);
    useEffect(() => {
        contact.from(contacth1.current, {
            duration: .6,
            skewX: 10,
            x: -100,
            opacity: 0
        }, "-=3.5")
        contact.from(contactimg.current, {
            duration: .5,
            y: -200,
            opacity: 0
        }, "-=3")
    }, [])


    return (
        <div>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Transition timeline={contact} />
            <div className="contact-image contact-overlay" ref={contactimg}></div>
            <div className="container-contact">
                <h1 ref={contacth1}>Contact Page</h1>
            </div>
        </div>
    )

}

export default contact